"""Structured data service that bypasses OCR and model inference.

Facade module: the implementation now lives in domain-split siblings —
structured_common (shared primitives), structured_files (upload/discovery/readers),
structured_connections (database connections), structured_profile (column profiling
+ policy recommendation), structured_masking (preview + value redaction) and
structured_delivery (export jobs, format writers, delivery zip).

This module stays the single public import surface: callers and tests keep
importing — and monkeypatching — app.services.structured_service.
"""
from __future__ import annotations

import logging

from app.core.config import settings
from app.services.structured_common import (
    MAX_EXPORT_ROWS,
    MAX_PREVIEW_ROWS,
    MAX_PROFILE_ROWS,
    SUPPORTED_FILE_EXTENSIONS,
    LoadedTable,
    cell_to_json,
    compact_text,
    infer_runtime_type,
    infer_shape_kind,
    is_number_like,
    normalize_value,
    quote_sqlite_ident,
    safe_filename,
    stringify_cell,
    utc_iso,
)
from app.services.structured_connections import (
    annotate_discovered_connection_datasets,
    build_sqlalchemy_url,
    connection_display_metadata,
    create_connection,
    credential_key_path,
    decrypt_credential,
    discover_connection_datasets,
    discover_connection_datasets_from_payload,
    encrypt_credential,
    quote_sa_table,
    read_connection_table,
    register_connection_datasets,
    sqlalchemy,
    stable_discovered_dataset_id,
    test_connection,
)
from app.services.structured_delivery import (
    build_job_export_zip,
    export_base_filename,
    export_dataset,
    run_structured_job_item,
    sql_literal,
    structured_item_meta,
    unique_export_filename,
)
from app.services.structured_files import (
    copy_stream_with_limit,
    dataset_payload,
    detect_csv_encoding,
    discover_file_datasets,
    discover_sqlite_datasets,
    discover_xlsx_datasets,
    extension_kind,
    get_upload_dir,
    iter_dataset_rows,
    load_dataset_rows,
    normalize_columns,
    read_csv,
    read_jsonl,
    read_sqlite_table,
    read_xlsx_sheet,
    register_file_source,
    save_structured_upload_stream,
)
from app.services.structured_masking import (
    bucket_value,
    generalize_value,
    mask_keep_edges,
    mask_value,
    preview_dataset,
    redact_row,
    redact_value,
    stable_digest,
)
from app.services.structured_profile import (
    blocks_business_descriptor,
    build_structured_ner_text,
    choose_classification,
    classify_by_name,
    classify_by_values,
    default_policy,
    entity_matches_sample,
    get_or_create_policy,
    has_text_semantic_ready,
    infer_column_semantics_with_has,
    is_business_descriptor_column,
    is_identifier_column_name,
    is_probable_technical_identifier,
    map_has_entities_to_columns,
    max_risk,
    merge_semantic_column_profiles,
    normalize_structured_entity_type,
    profile_column,
    profile_dataset,
    recommended_action,
    sample_looks_semantic,
    save_policy,
    should_apply_semantic_profile,
    should_include_column_for_structured_semantics,
    validate_policy_columns,
)
from app.services.structured_store import StructuredStore, get_structured_store

logger = logging.getLogger(__name__)

__all__ = [
    "LoadedTable",
    "MAX_EXPORT_ROWS",
    "MAX_PREVIEW_ROWS",
    "MAX_PROFILE_ROWS",
    "SUPPORTED_FILE_EXTENSIONS",
    "StructuredStore",
    "annotate_discovered_connection_datasets",
    "blocks_business_descriptor",
    "bucket_value",
    "build_job_export_zip",
    "build_sqlalchemy_url",
    "build_structured_ner_text",
    "cell_to_json",
    "choose_classification",
    "classify_by_name",
    "classify_by_values",
    "compact_text",
    "connection_display_metadata",
    "copy_stream_with_limit",
    "create_connection",
    "credential_key_path",
    "dataset_payload",
    "decrypt_credential",
    "default_policy",
    "detect_csv_encoding",
    "discover_connection_datasets",
    "discover_connection_datasets_from_payload",
    "discover_file_datasets",
    "discover_sqlite_datasets",
    "discover_xlsx_datasets",
    "encrypt_credential",
    "entity_matches_sample",
    "export_base_filename",
    "export_dataset",
    "extension_kind",
    "generalize_value",
    "get_or_create_policy",
    "get_structured_store",
    "get_upload_dir",
    "has_text_semantic_ready",
    "infer_column_semantics_with_has",
    "infer_runtime_type",
    "infer_shape_kind",
    "is_business_descriptor_column",
    "is_identifier_column_name",
    "is_number_like",
    "is_probable_technical_identifier",
    "iter_dataset_rows",
    "load_dataset_rows",
    "map_has_entities_to_columns",
    "mask_keep_edges",
    "mask_value",
    "max_risk",
    "merge_semantic_column_profiles",
    "normalize_columns",
    "normalize_structured_entity_type",
    "normalize_value",
    "preview_dataset",
    "profile_column",
    "profile_dataset",
    "quote_sa_table",
    "quote_sqlite_ident",
    "read_connection_table",
    "read_csv",
    "read_jsonl",
    "read_sqlite_table",
    "read_xlsx_sheet",
    "recommended_action",
    "redact_row",
    "redact_value",
    "register_connection_datasets",
    "register_file_source",
    "run_structured_job_item",
    "safe_filename",
    "sample_looks_semantic",
    "save_policy",
    "save_structured_upload_stream",
    "settings",
    "should_apply_semantic_profile",
    "should_include_column_for_structured_semantics",
    "sql_literal",
    "sqlalchemy",
    "stable_digest",
    "stable_discovered_dataset_id",
    "stringify_cell",
    "structured_item_meta",
    "test_connection",
    "unique_export_filename",
    "utc_iso",
    "validate_policy_columns",
]
